### ISSUE TITLE
Reach out to Sam Hinkie via Slack ASAP

### ISSUE THREAD

**Issue by JBB** [cs210/SA#1]
Team, I talked with Sam today and he's wondering why you haven't reached out. Let's go, team!! Get with the program.  Here are some [guidelines](https://github.com/cs210/Home/blob/master/Assignments/05-Meet%20with%20Liaisons/connect-with-liaisons.md).  I'd suggest sending an email AND a setting up a Slack.

**Comment by dillonfranke** [comment]
Thanks Jay, we sent an email including the Slack join link. Feel free to join the Slack yourself in order to stay up to date with our latest progress. (You are cc'd on the email)
